### ISSUE TITLE
Adding cards to the Firefox Trello board

### ISSUE THREAD

**Issue by thomaselin** [mozilla/bug-handling#11]
What's the reasoning behind this requirement? 

- Any bug controlled by the behind-pref flag must be added to the Firefox Feature Trello board

The purpose of the Firefox Trello board is to track significant changes/impacts across the delivery of the product. While many of these significant features have a pref process involved. Not every feature that lands behind a pref is significant enough to warrant this level of exposure/tracking.

I'd ask that we punt this requirement out of the policy for now and re-assess once folks have adopted the process. That way we'll have data around what/how many cards we're talking about adding and what value it would bring to the Firefox Trello.

**Comment by emceeaich** [comment]
This was a request from DCamp's directors, I'm wary of removing it until we discuss further.

**Comment by emceeaich** [comment]
Some more context for why that rule came up. In https://docs.google.com/document/d/14VtMlSoln4mXj0Fjk9YmoBu7OJfSJzW7pvTLScvF1ps/edit?ts=5a99f0d6#, "Trello cards will explicitly answer a question whether a feature is behind a preference or not."

However, this version of the policy will be replaced with the feature tracking policy, a project that is kicked off tomorrow, so I'm going to close this for now.
