### ISSUE TITLE
Handling auto-disable pref situations

### ISSUE THREAD

**Issue by thomaselin** [mozilla/bug-handling#2]
Just wondering how this process would work when a feature is enabled by default in Nightly  but set to auto-disable in Beta/Release? The Layout team commonly uses this tactic to test new features in Nightly and gather feedback.

When the feature is ready they then land a bug that removes the auto-disable and let's the feature ride the trains pref'd ON by default.

Example; Shapes outside
layout.css.shape-outside.enabled
Bug to enable in Nightly only (https://bugzilla.mozilla.org/show_bug.cgi?id=1353631)
Bug filed to remove auto-disable in Beta and Release (https://bugzilla.mozilla.org/show_bug.cgi?id=1457297)

**Comment by emceeaich** [comment]
And we don't use a feature flag server for this, we set the prefs in the
build?

**Comment by pascalchevrel** [comment]
> And we don't use a feature flag server for this, we set the prefs in the build?

yes, the channel specific build-defines are documented here:
https://wiki.mozilla.org/Platform/Channel-specific_build_defines

**Comment by emceeaich** [comment]
@thomaselin, I'm going to draft a PR which tries to describe this workflow, cribbing from your description, and ask for your review.

**Comment by emceeaich** [comment]
I'm going to close this as this version of the Features Flags work is obsoleted by the Feature Tracking work.
