### ISSUE TITLE
Handling brave-users/developers-only features controlled by a pref

### ISSUE THREAD

**Issue by froydnj** [mozilla/bug-handling#3]
This is similar in spirit to #2: we have occasionally had features that are not enabled on any channel, but are pref-controlled, so that brave users can flip the pref and provide feedback.  Or perhaps developers would like to incrementally land features that are known not to work, but it makes work on the feature more convenient: Nightlies can be used for testing, and the patches can be reviewed incrementally without building a huge patch stack.  Pieces of Quantum DOM were landed under this model, and I believe some bits of WebRender and Stylo were as well.

What would the policy require in such cases?  Would the process need to be followed for flipping the feature on by default in Nightly, or just when the feature is deemed ready to ride the train from Nightly to Beta?

**Comment by emceeaich** [comment]
I think this would be resolved by the changes to the `behind-pref` flag discussed in #5.
