### ISSUE TITLE
Do stalled bugs should loose their priority

### ISSUE THREAD

**Issue by nils-ohlmeier** [mozilla/bug-handling#39]
Currently the triage guidelines say:
"The priority of stalled bugs should be ‘–’ but other keywords may apply to them."
which is a little bit surprising depending on your point of view.

As an example: if we have a P1 sec bug which gets stalled. Why should it loose it's P1 marking (for sec bugs mostly based on the sec level rating) "just" because it's stalled for now? It's rather unlikely that when new information arrives the sec-rating of the bug has changed and therefore the priority needs to change.

On the other hand I see it as a possible advantage if resetting the priority results in stalled bugs to get triaged again after new information arrives.

Maybe another option would be to leave the priority as is when adding the stalled keyword. But if new information arrives removed the stalled keyword and reset the priority at the same time to enable/trigger re-triaging.

**Comment by emceeaich** [comment]
I think resetting priority once a bug gets un-stalled is the right approach. We do need to make sure the triage owner is aware of the bug once that happens (the bug is most likely older than the the current release version and would not show up in Are We Triaged Yet).

**Comment by emceeaich** [comment]
https://github.com/mozilla/relman-auto-nag/issues/595
