### ISSUE TITLE
Feature-flags policy needs clarification

### ISSUE THREAD

**Issue by Standard8** [mozilla/bug-handling#4]
I'm confused by the feature-flags policy on a couple of points:

- Myself and other engineers have always been told to set qe-verify+ to request QE to verify a bug. qe-verify? is a "this might need verification, give us details". QE would then come along to a qe-verify+ bug and mark it as verified when complete. This appears to [match the original intent](https://mail.mozilla.org/pipermail/firefox-dev/2014-August/002131.html).
- The policy seems to imply that all the work for initial landing of, and then enabling the pref, is done in one bug. We generally land only one set of patches per bug, so this would be in conflict.

I would have expected something like:

- Meta bug for the work, which will end up enabling the pref. This would have the behind-pref+ flag set.
- Individual bug(s) blocking the meta that implement the new feature & fixing issues as they are found. One or more of these bugs would be marked qe-verify+ and QE would then verify them.
- Once the work is "completed", maybe some form of final verification option, or verify after the pref turn on is actually landed.
- The meta bug then gets the patch to enable the pref, and lands as normal.

**Comment by mnoorenberghe** [comment]
> The policy seems to imply that all the work for initial landing of, and then enabling the pref, is done in one bug. We generally land only one set of patches per bug, so this would be in conflict.

Yeah, this also a concern of mine about the proposal. For example, for the development of Payment Request we would have had to set that flag on 134 resolved bugs and probably another 80+ bugs yet to be resolved bugs before we ride the trains. That doesn't seem very scalable. Perhaps the documentation just isn't clear because the example is for a small change.

**Comment by emceeaich** [comment]
As per [my email from May 4th](https://groups.google.com/d/msg/mozilla.dev.platform/dmxplqO0zQA/VEbiFE__DgAJ), I will update the policy to reflect that feature work may have multiple bugs needed to land it.

I've asked Tom G. for QA's clarification of the `qe-verify` flag's use.
