### ISSUE TITLE
Missing promised GitHub triage guidance

### ISSUE THREAD

**Issue by hwine** [mozilla/bug-handling#46]
The [main triage doc](https://github.com/mozilla/bug-handling/blob/master/_policies/triage-bugzilla.md#my-project-is-on-github) promises some information on GitHub practices. But there is no link, PR, or open issue (well, there is now).

I'm mostly interested in the equivalent queries for bugs-needing-triage in GitHub. I don't think the query language for issues is rich enough to translate the Bugzilla queries, and suspect some additional label may be needed.

**Comment by emceeaich** [comment]
Link is https://firefox-bug-handling.mozilla.org/labels
