### ISSUE TITLE
Should `behind-pref` be a status flag?

### ISSUE THREAD

**Issue by emceeaich** [mozilla/bug-handling#5]
At the moment, `behind-pref` is set up as a simple flag. This presumes that features will ride trains, but we may want to enable features in Nightly for a number of releases, but not turn them on in Beta or Release (see #3).

Using a status flag (with multiple values) allows us to specify where a feature is active. This flag would be set on the bug for the feature (if there's a single feature) or the [meta] bug for the whole feature.

One set of values to use could be:

---:  not a feature that should be controlled by a pref
?: is this a feature that should be controlled by a pref
planned: this is a feature that should be controlled by a pref, but code has not landed yet (the value of target milestone on the bug would be `future`)
in-progress: this is a feature that should be controlled by a pref, code has landed but the feature should not be enabled
nightly: the feature should be enabled in nightly
beta: the feature should be enabled in nightly and beta
release: the feature should be enabled in nightly, beta, and release
esr: the feature should be enabled in in nightly, beta, release and esr
inactive: the feature has been disabled in all version

I don't want to have a flag per numeric version of this flag because it's a version management headache

**Comment by rkothari19** [comment]
I'd suggest using a value like Nightly61, Beta60, Release59, rather than just Nightly, Beta, Release. The concatenated string serves two purpose: 1) version info and 2) which stabilization cycle for this version had the feature on/off.

**Comment by froydnj** [comment]
Thanks for writing this up.  A more fine-grained flag seems useful.

When would the `release` value get set?  When the feature is planned to ship in release, or when a release with that feature active is actually released?  Likewise for the `esr` flag: would we set `esr` when we intend for the next ESR to ship with the feature or would we change all bugs with the flag value set to `release` to `esr` when a new ESR is released?  The latter option in both cases (and for `beta`, too, I suppose) would generate a flood of mostly-useless bugmail.

(I think there is value in having a separate designation for ESR; there are probably features that we may not want active in the ESR for whatever reason, even if those features are rare.  But I'm unsure of how often that would actually occur.)

**Comment by emceeaich** [comment]
Thanks for your patience while I catch up with requests and comments. 

If I understand @rkothari19's suggestion, then `behind-pref` becomes a release status flag with values:

- `---`
- `in-progress`
- `off`
- `release60`
- `beta61`
- `nightly62`

then on merge day we would add

- `release61`
- `beta62`
- `nightly63`

and disable (but not delete) `release60`, `beta61`, and `nightly62`.

Then the leads for the feature would need to update the flags appropriately until the bug is closed.

and @froydnj suggests a similar arrangement for the ESR releases where we have a `behind-pref-esr` flag which would have the values

- `---`
- `off`
- `52`
- `60`

And would only had values added and removed when there's a new ESR release. 

I can create a PR to the policy for this and request y'all review of it.
