### ISSUE TITLE
Maiking it clearer who/when file a bug to enable the feature in Nightly and/or Beta/Release

### ISSUE THREAD

**Issue by masayuki-nakano** [mozilla/bug-handling#7]
> RelMan and product management decide if the feature will be enabled in Nightly, then:
> 
>  - The patch to flip the pref on should be attached to the "Make Tabby Cats the new default tab experience" bug

This explanation does not say that what will be done by RelMan or product management when they decide the feature can be enabled in Nightly and/or Beta/Release.

Does a developer who works on implementing the feature should file a bug to enable the feature when he/she wants to enable it in some channels and does it become additional review request for RelMan and product management?

Or, after QA moves the bug which implemented the feature behind the pref to VERIFIED, does that mean that RelMan and product management decide the feature can be enabled in Nightly?

**Comment by emceeaich** [comment]
Once the bug for the feature has reached RESOLVED VERIFIED, then the lead for the feature which may be an engineer, a program manager, or a product manager **must** confirm with the Nightly Release Manager, and then enable it. 

The question is if this done through a compiler define or a pref, see issue #2.

**Comment by emceeaich** [comment]
I'll also clear up the language in that paragraph.
